language: python

dist: xenial

python:
    - "3.5"
    - "3.6"
    - "3.7"

env:
    - ASYNC_TEST_TIMEOUT=30

services:
    - postgresql
    - mysql

before_install:
    - pip install --upgrade pip
    - pip install poetry

install:
    - poetry install

before_script:
    - psql -U postgres < tests/travis/postgre.sql
    - mysql --user=root --password=''  < tests/travis/my.sql

script:
    - make lint-flake8
    - if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then make lint-black; fi
    - make test
